# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
      - karthequian-patch-1



pool:
     name: AzureProdAse
     Agent.Name: prod-ase01-jump
# no PR triggers
pr: none


steps:

 - checkout: self
   fetchDepth: 1
 - task: ArchiveFiles@2
   name: Create_Zip
   inputs:
     rootFolderOrFile: '$(build.sourcesDirectory)'
     includeRootFolder: false
 - task: PublishBuildArtifacts@1


