apiVersion : apps/v1
kind: Deployment
metadata:
  name: sureshtekyentrahelloword 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sureshtekyentrahelloword
  template:
    metadata:
      labels:
        app: sureshtekyentrahelloword 
    spec:
      containers:
        - name: sureshtekyentrahelloword 
          image: myecrrepo.azurecr.io/sureshtekyentrahelloword
          ports:
          - containerPort: 80