# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - hellowordgithub(stage)

on:
  push:
    branches:
      - karthequian-patch-1
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu 18.04

    steps:
    - uses: actions/checkout@master


  
    -  uses: veracode/veracode-uploadandscan-action@0.2.1
       with:
    # appname
        appname: ${{ github.repository }}
    # createprofile
        createprofile: true
    # filepath
        filepath: .

    # vid
        vid: 12dd2522f09d13e76d5b03ff29fcae67
    # vkey
        vkey: adc2fb7d0cc6cfa27b12fb9d09472d1d281f11ab1271833899684df90c92efb7baaa93dc8aa3fc5ba1e761875964b73d739df3b5a57df27a3c36be2e861c6418
 

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'hellowordgithub'
        slot-name: 'stage'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_dcf6c4df55eb4020be68d864abb39e97 }}
        package: .
